#!/usr/bin/env bash
source "$(dirname "$0")"/fontlib.sh

# Mono Fonts
if [[ "$OSTYPE" == "darwin"* ]]; then
  deploy_font_gh source-code-pro ryanoasis/nerd-fonts 91d8a283d316fa38e440f24520ad6e5f93534a0c "**/SauceCodeProNerdFontMono*.ttf"
else
  deploy_font_gh source-code-pro adobe-fonts/source-code-pro 4bbbf01dcf69752d527dbad061e2977b30d0bee2 "OTF/*.otf" "VF/*.otf"
  deploy_font_gh nerd-fonts ryanoasis/nerd-fonts 91d8a283d316fa38e440f24520ad6e5f93534a0c patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf
fi
deploy_font_gh_release 3270 "rbanffy/3270font" "3270_fonts_d916271.zip" "*.otf"
deploy_font_gh_release cascadia-code "microsoft/cascadia-code" "CascadiaCode-2111.01.zip" "ttf/*.ttf"
deploy_font_archive perfect-dos-vga https://github.com/microsoft/terminal/files/9865167/RasterFonts.zip "*.ttf"
deploy_font_archive everson-mono https://www.evertype.com/emono/evermono.zip "**/Everson*.ttf"
deploy_font_archive jetbrains-mono "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip" "**/*.ttf"
deploy_font_gh_release iosvmata "N-R-K/Iosvmata" "Iosvmata-v1.2.0.tar.zst"  "**/Normal/*.ttf"
deploy_font_gh_release fira-code "tonsky/FiraCode" "Fira_Code_v6.2.zip" "**/*.ttf"

# Regular Fonts
deploy_font_gh et-book edwardtufte/et-book 65f78029d378dea4a864a395933988b49adf0be2 "et-book-ligatures-enabled/**/*.otf"
deploy_font_gh et-bembo DavidBarts/ET_Bembo master "ETBembo-*.otf"
deploy_font_gh_release eb-garamond "georgd/EB-Garamond" "EBGaramond.zip" "EBGaramond*.otf"

do_deploy
