#!/usr/bin/env bash
source "$(dirname "$0")"/fontlib.sh

# Mono Fonts
deploy_font_glob adobe-fonts/source-code-pro 4bbbf01dcf69752d527dbad061e2977b30d0bee2 "OTF/*.otf" "VF/*.otf"
deploy_font ryanoasis/nerd-fonts 91d8a283d316fa38e440f24520ad6e5f93534a0c patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf
deploy_font_glob_release "rbanffy/3270font" "3270_fonts_d916271.zip" "3270" "*.otf"
deploy_font_glob_release "microsoft/cascadia-code" "CascadiaCode-2111.01.zip" "cascadia-code" "ttf/*.ttf"

# Regular Fonts
deploy_font_glob edwardtufte/et-book 65f78029d378dea4a864a395933988b49adf0be2 "et-book-ligatures-enabled/**/*.otf"
deploy_font_glob DavidBarts/ET_Bembo master "ETBembo-*.otf"
deploy_font_glob_release "georgd/EB-Garamond" "EBGaramond.zip" "EB-Garamond" "EBGaramond*.otf"

do_deploy
