alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias c='cucumber -p rerun'
alias cw='cucumber -p wip'
alias ri='ri -f ansi'
alias fastcop='git since-develop | grep \\.rb$ | xargs ls 2>/dev/null | xargs rubocop --force-exclusion'
