format = """\
$battery\
$git_branch\
$git_commit\
$git_state\
$git_status\
$jobs\
$directory\
$character"""

[battery]
full_symbol = "🔋︎"
charging_symbol = "⚡︎"
discharging_symbol = "💀︎"
[[battery.display]]
threshold = 100
style = "yellow"

[character]
format = "$symbol "
success_symbol = "[\\$](bright-yellow)"
error_symbol = "[\\$](red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 0
style = "cyan"
[git_branch]
symbol = ""
format = "[$branch]($style)$symbol "
style = "blue"
[jobs]
format = "[$symbol]($style) "
style = "yellow"
symbol = "ꕚ"
