export HISTFILE="$HOME/.cache/bash_history"
export LESSHISTFILE="$HOME/.cache/less_history"
export PSQL_HISTORY="$HOME/.cache/psql_history"
export NODE_REPL_HISTORY="$HOME/.cache/node_repl_history"
export IRBRC="$HOME/.config/irb/irbrc"
export INPUTRC="$HOME/.config/readline/inputrc"
export XCOMPOSEFILE="$HOME/.config/X11/xcompose"
export XCOMPOSECACHE="$HOME/.cache/X11/xcompose"
