Plug 'kristijanhusak/orgmode.nvim'
Plug 'vim-scripts/utl.vim'
Plug 'tpope/vim-speeddating'
Plug 'inkarkat/vim-ingo-library'
Plug 'inkarkat/vim-SyntaxRange'
Plug 'mattn/calendar-vim'
Plug 'chrisbra/NrrwRgn'
