[tools]
node = "22"
python = "3"
ruby = "3"
rust = "latest"

bitwarden = "latest"
fzf = "latest"
starship = "latest"
yq = "latest"

"pipx:maestral" = { version= "latest", extras = "maestral-qt,python-systemd" }

"ubi:tinted-theming/tinty" = "latest"

[settings.python]
default_packages_file = "~/.config/mise/python_default_packages"
